binutils-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: binutils
  path: /targets/binutils/afl-clang-fast/readelf-afl-clang-fast
  suffix: afl-clang-fast
binutils-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: binutils
  path: /targets/binutils/afl-dyninst/readelf-dyninst
  suffix: afl-dyninst
binutils-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: binutils
  path: /targets/binutils/afl-gcc/readelf-afl-gcc
  suffix: afl-gcc
binutils-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: binutils
  path: /targets/binutils/afl-retrowrite/readelf-retrowrite
  suffix: afl-retrowrite
binutils-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: binutils
  path: /targets/binutils/gcc/readelf-gcc
  suffix: gcc
bzip2-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: bzip2
  path: /targets/bzip2/afl-clang-fast/bzip2-afl-clang-fast
  suffix: afl-clang-fast
bzip2-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: bzip2
  path: /targets/bzip2/afl-dyninst/bzip2-dyninst
  suffix: afl-dyninst
bzip2-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: bzip2
  path: /targets/bzip2/afl-gcc/bzip2-afl-gcc
  suffix: afl-gcc
bzip2-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: bzip2
  path: /targets/bzip2/afl-retrowrite/bzip2-retrowrite
  suffix: afl-retrowrite
bzip2-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: bzip2
  path: /targets/bzip2/gcc/bzip2-gcc
  suffix: gcc
file-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: file
  path: /targets/file/afl-clang-fast/file-afl-clang-fast
  suffix: afl-clang-fast
file-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: file
  path: /targets/file/afl-dyninst/file-dyninst
  suffix: afl-dyninst
file-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: file
  path: /targets/file/afl-gcc/file-afl-gcc
  suffix: afl-gcc
file-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: file
  path: /targets/file/afl-retrowrite/file-retrowrite
  suffix: afl-retrowrite
file-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: file
  path: /targets/file/gcc/file-gcc
  suffix: gcc
fuzz_targets:
- file-gcc
- file-afl-dyninst
- file-afl-retrowrite
- file-afl-gcc
- file-afl-clang-fast
- libpng-gcc
- libpng-afl-dyninst
- libpng-afl-retrowrite
- libpng-afl-gcc
- libpng-afl-clang-fast
- tcpdump-gcc
- tcpdump-afl-dyninst
- tcpdump-afl-retrowrite
- tcpdump-afl-gcc
- tcpdump-afl-clang-fast
- libtiff-gcc
- libtiff-afl-dyninst
- libtiff-afl-retrowrite
- libtiff-afl-gcc
- libtiff-afl-clang-fast
- libarchive-gcc
- libarchive-afl-dyninst
- libarchive-afl-retrowrite
- libarchive-afl-gcc
- libarchive-afl-clang-fast
- bzip2-gcc
- bzip2-afl-dyninst
- bzip2-afl-retrowrite
- bzip2-afl-gcc
- bzip2-afl-clang-fast
- binutils-gcc
- binutils-afl-dyninst
- binutils-afl-retrowrite
- binutils-afl-gcc
- binutils-afl-clang-fast
libarchive-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libarchive
  path: /targets/libarchive/afl-clang-fast/bsdtar-afl-clang-fast
  suffix: afl-clang-fast
libarchive-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: libarchive
  path: /targets/libarchive/afl-dyninst/bsdtar-dyninst
  suffix: afl-dyninst
libarchive-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libarchive
  path: /targets/libarchive/afl-gcc/bsdtar-afl-gcc
  suffix: afl-gcc
libarchive-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libarchive
  path: /targets/libarchive/afl-retrowrite/bsdtar-retrowrite
  suffix: afl-retrowrite
libarchive-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: libarchive
  path: /targets/libarchive/gcc/bsdtar-gcc
  suffix: gcc
libpng-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libpng
  path: /targets/libpng/afl-clang-fast/pngfix-afl-clang-fast
  suffix: afl-clang-fast
libpng-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: libpng
  path: /targets/libpng/afl-dyninst/pngfix-dyninst
  suffix: afl-dyninst
libpng-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libpng
  path: /targets/libpng/afl-gcc/pngfix-afl-gcc
  suffix: afl-gcc
libpng-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libpng
  path: /targets/libpng/afl-retrowrite/pngfix-retrowrite
  suffix: afl-retrowrite
libpng-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: libpng
  path: /targets/libpng/gcc/pngfix-gcc
  suffix: gcc
libtiff-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libtiff
  path: /targets/libtiff/afl-clang-fast/tiff2rgba-afl-clang-fast
  suffix: afl-clang-fast
libtiff-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: libtiff
  path: /targets/libtiff/afl-dyninst/tiff2rgba-dyninst
  suffix: afl-dyninst
libtiff-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libtiff
  path: /targets/libtiff/afl-gcc/tiff2rgba-afl-gcc
  suffix: afl-gcc
libtiff-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: libtiff
  path: /targets/libtiff/afl-retrowrite/tiff2rgba-retrowrite
  suffix: afl-retrowrite
libtiff-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: libtiff
  path: /targets/libtiff/gcc/tiff2rgba-gcc
  suffix: gcc
tcpdump-afl-clang-fast:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: tcpdump
  path: /targets/tcpdump/afl-clang-fast/tcpdump-afl-clang-fast
  suffix: afl-clang-fast
tcpdump-afl-dyninst:
  fuzz_cmd: afl-fuzz-dyninst.sh -i $fuzz_in -o $fuzz_out
  key: tcpdump
  path: /targets/tcpdump/afl-dyninst/tcpdump-dyninst
  suffix: afl-dyninst
tcpdump-afl-gcc:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: tcpdump
  path: /targets/tcpdump/afl-gcc/tcpdump-afl-gcc
  suffix: afl-gcc
tcpdump-afl-retrowrite:
  fuzz_cmd: afl-fuzz -i $fuzz_in -o $fuzz_out
  key: tcpdump
  path: /targets/tcpdump/afl-retrowrite/tcpdump-retrowrite
  suffix: afl-retrowrite
tcpdump-gcc:
  fuzz_cmd: afl-fuzz -Q -i $fuzz_in -o $fuzz_out
  key: tcpdump
  path: /targets/tcpdump/gcc/tcpdump-gcc
  suffix: gcc
